### ISSUE TITLE
Figma do Grupo 02 - PDV

### ISSUE THREAD

**Issue by glaucotodesco** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#10]
[Curso Figma](https://www.cursae.com.br/cursos/figma-criando-interfaces-do-zero-ate-o-prototipo-final
)

Líder: João Otávio
Gustavo Andrelo
Cauã
Jorge
Felipe
Yuuya

**Comment by cipher757** [comment]
Link do Projeto no Figma: https://www.figma.com/file/ykBTDgQtwBpHgb1gDtGlD6/Projeto---PDV---Fatec?type=design&t=wigygsw820lSkc1z-6
