### ISSUE TITLE
Figma do Grupo01 - Administrativo

### ISSUE THREAD

**Issue by glaucotodesco** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#11]
[Curso Figma](https://www.cursae.com.br/cursos/figma-criando-interfaces-do-zero-ate-o-prototipo-final
)

Líder: Pedro Vinícius
Maria Eduarda
Vinicius
João Vitor
Erick

**Comment by vinisvp** [comment]
Link do projeto do Figma: https://www.figma.com/files/project/216143289/Team-project?fuid=1283439623835847450
