### ISSUE TITLE
Apresentação do Projeto - PowerPoint

### ISSUE THREAD

**Issue by glaucotodesco** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#15]
Baseado no Figma, construir a apresentação do projeto no PowerPoint ou equivalente.
https://www.canva.com/design/DAGFOfH0kOw/RldI64W_bCfwKz_5y1cBlw/edit?utm_content=DAGFOfH0kOw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Bananadev3** [comment]
Link apresentação Canvas: [Projeto Easy Coast](https://www.canva.com/design/DAGFOfH0kOw/u1cjHXjroLe9RH3Ainz8Gw/view?utm_content=DAGFOfH0kOw&utm_campaign=designshare&utm_medium=link&utm_source=editor)

**Comment by luukinhaaa** [comment]
https://www.canva.com/design/DAGFOfH0kOw/RldI64W_bCfwKz_5y1cBlw/edit
