### ISSUE TITLE
Figma Grupo 04 - EasyCoast (Tela da Nossa Empresa)

### ISSUE THREAD

**Issue by JuliaCanavezzi** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#16]

**Comment by Gustavo-andrelo** [comment]
https://www.figma.com/design/59bcmMhh7m5PHxqwLiRR58/Untitled?node-id=0%3A1&t=0JYAojW1B52WvAfD-1
Link do figma para visualização

**Comment by vinisvp** [comment]
Figma: https://www.figma.com/design/59bcmMhh7m5PHxqwLiRR58/Untitled?node-id=0%3A1&t=0JYAojW1B52WvAfD-1
