### ISSUE TITLE
Épicos, Features e Personas - PDV

### ISSUE THREAD

**Issue by cipher757** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#19]

**Comment by cipher757** [comment]
[Épicos_Features_Personas_PDV.pptx](https://github.com/user-attachments/files/15792969/Epicos_Features_Personas_PDV.pptx)

**Comment by joao-silva-d3v** [comment]
https://www.figma.com/board/aGG6eb30wHPdnC1oBNawTF/Planejamento-Easy-Coast?node-id=0-1&t=4HdhXp5fuQjyVQCE-1
