### ISSUE TITLE
Garçom - User Stories, Personas e Épico

### ISSUE THREAD

**Issue by Bananadev3** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#20]

**Comment by vinisvp** [comment]
Link dos épicos e features: https://www.figma.com/board/aGG6eb30wHPdnC1oBNawTF/%C3%89picos-e-features?node-id=0-1&t=PjwyeNzX4sLSVqW7-1

**Comment by rafaScalet** [comment]
link> https://www.figma.com/design/mDZGrJOh3zRqz2ilqCsy3R/Untitled?node-id=0-1&t=ZWS6SsLuxII51h3r-0
