### ISSUE TITLE
Formas de Monetização/Modelo de negócio

### ISSUE THREAD

**Issue by vinisvp** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#6]
Registrar no documento as formas de monetização e modelos de negócio do projeto.

**Comment by cipher757** [comment]
Fonte de estudo que pode ser usado: 
https://olist.com/blog/pt/como-vender-mais/inteligencia-competitiva/como-atrair-mais-clientes/ 
https://epoc.com.br/blog/faturamento/#:~:text=Mas%2C%20de%20maneira%20geral%2C%20temos,180%20mil%20%E2%80%93%20R%24%20500%20mil
https://saipos.com/sistema/restaurante/montar-restaurante/plano-de-negocio-para-restaurante
