### ISSUE TITLE
Principais dores

### ISSUE THREAD

**Issue by luukinhaaa** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#7]

**Comment by cipher757** [comment]
Fonte de estudo que pode ser usado:
https://saipos.com/sistema/restaurante/montar-restaurante/plano-de-negocio-para-restaurante

**Comment by cipher757** [comment]
Fonte de estudo que pode ser usado:
https://saipos.com/sistema/restaurante/montar-restaurante/plano-de-negocio-para-restaurante

**Comment by MariaMariEdu** [comment]
[Dores_cliente.txt](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/files/15311938/Dores_cliente.txt)
