### ISSUE TITLE
Quantidade e descrição das tabelas no banco de dados

### ISSUE THREAD

**Issue by vinisvp** [glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024#9]
Uma definição inicial de cimo será o banco de dados do projeto, como as tabelas e relacionamentos

**Comment by YuuyaOkatani** [comment]
Protótipo banco de dados no SQL Server 2.0 feito! 



[bd projeto integrador 2.0.txt](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/files/15355305/bd.projeto.integrador.2.0.txt)



![Image](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/assets/114952688/a0a3b05a-24b1-4deb-bcb3-62a37a377875)

**Comment by YuuyaOkatani** [comment]
Banco de dados no SQL Server Protótipo 2.0 feito!


![Image](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/assets/114952688/dc32bfbb-7bda-4865-b73b-55c83d524bcb)



[bd projeto integrador 2.0.txt](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/files/15355361/bd.projeto.integrador.2.0.txt)

**Comment by YuuyaOkatani** [comment]
![Image](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/assets/114952688/6f83bb23-d0fc-46c0-9bc8-8a372f6dd443)

UML atualizado do protótipo SQL 2.0

**Comment by YuuyaOkatani** [comment]
UML atualizado do protótipo SQL 2.0!



![Image](https://github.com/glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024/assets/114952688/7acbae75-5dfb-4a40-adc3-3cb477af1b77)
